name: mlops-california-housing
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - scikit-learn
  - mlflow
  - flask
  - dvc
  - kaggle
  - pip
  - pip:
      - prometheus_client
      - kaggle

