name: Train, Register, and Containerize California Housing API

on:
  push:
    branches:
      - main

jobs:
  train-and-model-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: mlops-california-housing
          cache-environment: true

      - name: Train and register model
        shell: bash -l {0}
        run: |
          micromamba activate mlops-california-housing
          python main_california_housing.py

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            models/
            models.config

  containerise-and-push:
    runs-on: ubuntu-latest
    needs: train-and-model-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download model artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/california-housing-api:latest

  pull-and-run-docker:
    runs-on: ubuntu-latest
    needs: containerise-and-push

    steps:
      - name: Pull latest Docker image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/california-housing-api:latest

      - name: Stop running container if exists
        run: |
          docker ps -q --filter "name=california-housing-api" | grep -q . && docker stop california-housing-api && docker rm california-housing-api || echo "No running container to stop."

      - name: Run latest container
        run: |
          docker run -d --name california-housing-api -p 5001:5001 ${{ secrets.DOCKERHUB_USERNAME }}/california-housing-api:latest